USE PIZZA;

# 1. How many unique pizza Ids are present?
SELECT COUNT(PIZZA_ID) FROM PIZZA_SALES;

# 2. How many total orders place?
SELECT COUNT(ORDER_ID) FROM PIZZA_SALES;

# 3. How many total unique orders placed?
SELECT COUNT(DISTINCT ORDER_ID) FROM PIZZA_SALES;

# 4. What are Total quntities of pizza ordered?
SELECT SUM(QUANTITY) FROM PIZZA_SALES;

# 5. What is the Maximum and minimum quantities ordered?
SELECT MAX(QUANTITY) AS MAX_QUANTITY, MIN(QUANTITY) AS MIN_QUANTITY FROM PIZZA_SALES;

# 6. What is the Count of the number of unique quantity ordered by sum of Quantity?
SELECT DISTINCT QUANTITY, COUNT(QUANTITY) FROM PIZZA_SALES
GROUP BY QUANTITY;

# 7. What are the different pizza names?
SELECT DISTINCT PIZZA_NAME_ID FROM PIZZA_SALES;

# 8. What is the total quantity of different names of pizzas ordered?
SELECT DISTINCT PIZZA_NAME_ID, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_NAME_ID;

# 9. Name top 10 pizza names which people loves the most?
SELECT DISTINCT PIZZA_NAME_ID, SUM(QUANTITY) AS TOTAL_PIZZAS FROM PIZZA_SALES
GROUP BY PIZZA_NAME_ID
ORDER BY TOTAL_PIZZAS DESC
LIMIT 10;

# 10. Name the pizza which people ordered vey less time?
SELECT DISTINCT PIZZA_NAME_ID, SUM(QUANTITY) AS TOTAL_PIZZAS FROM PIZZA_SALES
GROUP BY PIZZA_NAME_ID
ORDER BY TOTAL_PIZZAS
LIMIT 1;

# 11. Calculate per order quantity?
SELECT SUM(QUANTITY)/COUNT(DISTINCT ORDER_ID) AS AVERAGE_QUANTITY_ORDERED FROM PIZZA_SALES;

# 12. Find the dates from which we have records for pizza sales?
SELECT MAX(ORDER_DATE), MIN(ORDER_DATE) FROM PIZZA_SALES;

# 13. On which date maximum quantities of pizza ordered?
SELECT ORDER_DATE, SUM(QUANTITY) AS TOTAL_PIZZA FROM PIZZA_SALES
GROUP BY ORDER_DATE
ORDER BY TOTAL_PIZZA DESC
LIMIT 1;

# 14. On which date MINIMUM quantities of pizza ordered?
SELECT ORDER_DATE, SUM(QUANTITY) AS TOTAL_PIZZA FROM PIZZA_SALES
GROUP BY ORDER_DATE
ORDER BY TOTAL_PIZZA
LIMIT 1;

# 15. On which date maximum orders placed?
SELECT ORDER_DATE, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY ORDER_DATE
ORDER BY TOTAL_ORDERS DESC
LIMIT 1;

# 16. On which date minimum orders placed?
SELECT ORDER_DATE, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY ORDER_DATE
ORDER BY TOTAL_ORDERS
LIMIT 1;

# 17. Busiest time SLOT for pizza store?
SELECT CASE WHEN TIME(ORDER_TIME) BETWEEN '09:00:00' AND '12:00:00' THEN 'MORNING'
     WHEN TIME(ORDER_TIME) BETWEEN '12:00:00' AND '16:00:00' THEN 'AFTERNOON'
     WHEN TIME(ORDER_TIME) BETWEEN '16:00:00' AND '20:00:00' THEN 'EVENING'
     WHEN TIME(ORDER_TIME) BETWEEN '20:00:00' AND '23:59:59' THEN 'LATE NIGHT'
     END ORDER_TIME_ZONE, SUM(QUANTITY) AS TOTAL_QUANTIES FROM PIZZA_SALES
     GROUP BY ORDER_TIME_ZONE
     ORDER BY TOTAL_QUANTIES DESC;

# 18. What is maximum and minimum pizza price?
SELECT MAX(UNIT_PRICE) AS MAXIMUM_PRICE, MIN(UNIT_PRICE) AS MINIMUM_PRICE FROM PIZZA_SALES;

# 19. Calculate average pizza price?
SELECT ROUND(AVG(UNIT_PRICE), 2) FROM PIZZA_SALES;

# 20. Which pizza is more affordable?
SELECT PIZZA_NAME_ID, MIN(UNIT_PRICE) AS PRICE_OF_PIZZA FROM PIZZA_SALES
GROUP BY PIZZA_NAME_ID
ORDER BY PRICE_OF_PIZZA
LIMIT 1;

# 21. Show me that order id which spend most for buying pizzas?
SELECT ORDER_ID, SUM(TOTAL_PRICE) AS TOTAL_PRICE FROM PIZZA_SALES
GROUP BY ORDER_ID
ORDER BY TOTAL_PRICE DESC
LIMIT 1;

# 22. Show me that order id which spend LEAST for buying pizzas?
SELECT ORDER_ID, SUM(TOTAL_PRICE) AS TOTAL_PRICE FROM PIZZA_SALES
GROUP BY ORDER_ID
ORDER BY TOTAL_PRICE
LIMIT 1;

# 23. How many quantities ordered for each pizza size?
SELECT PIZZA_SIZE, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

# 24. Number of total orders placed for each pizza size?
SELECT PIZZA_SIZE, COUNT(ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

# 25. Name the pizza name in every pizza size which is affordable? (fIND THE ANSWER IF YOU CAN)
#SELECT DISTINCT PIZZA_SIZE, PIZZA_NAME, MIN(UNIT_PRICE) AS PRICE_OF_PIZZA FROM PIZZA_SALES
#GROUP BY PIZZA_NAME, PIZZA_SIZE;

# 26. For which pizza category most orders are placed? Return all pizza categories by pizza orders by descresing order.
SELECT PIZZA_CATEGORY, COUNT(ORDER_ID) AS NUMBER_OF_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY
ORDER BY NUMBER_OF_ORDERS DESC;

# 27. Find out Number of quantities ordered for each category of pizza?
SELECT PIZZA_CATEGORY, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

# 28. Number of quntities of pizza sold for each pizza size in each category?
SELECT PIZZA_SIZE, PIZZA_CATEGORY, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY PIZZA_SIZE, PIZZA_CATEGORY;

# 29. Calculate average, max, min unit pizza price for each pizza size?
SELECT PIZZA_SIZE, MIN(UNIT_PRICE), MAX(UNIT_PRICE), AVG(UNIT_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

# 30. Calculate average, max, min total price for each pizza size?
SELECT PIZZA_SIZE, MIN(TOTAL_PRICE), MAX(TOTAL_PRICE), AVG(TOTAL_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

# 31. Calculate average, max, min unit pizza price for each pizza category?
SELECT PIZZA_CATEGORY, MIN(UNIT_PRICE), MAX(UNIT_PRICE), AVG(UNIT_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

# 32. Calculate average, max, min total price for each pizza category?
SELECT PIZZA_CATEGORY, MIN(TOTAL_PRICE), MAX(TOTAL_PRICE), AVG(TOTAL_PRICE) FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

# 33. What are the DIFFERENT pizzas are available?
SELECT DISTINCT PIZZA_NAME FROM PIZZA_SALES;

# 34. Find out Pizzas by total quantities ordered?
SELECT DISTINCT PIZZA_NAME, SUM(QUANTITY) FROM PIZZA_SALES
GROUP BY PIZZA_NAME;

# 35. Name top 10 pizzas which people loves to buy?
SELECT DISTINCT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_PIZZAS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_PIZZAS DESC
LIMIT 10;

# 36. Name the pizza which people ordered vey less time?
SELECT DISTINCT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_PIZZAS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_PIZZAS
LIMIT 1;

# 37. Change Pizza size if "S" then "Small" etc.
SELECT DISTINCT PIZZA_SIZE, 
CASE PIZZA_SIZE WHEN 'S' THEN 'SMALL'
                WHEN 'M' THEN 'MEDIUM'
				WHEN'L' THEN 'LARGE'
                WHEN'XL' THEN 'EXTRA LARGE'
				WHEN 'XXL' THEN 'DOUBLE EXTRA LARGE'
				END PIZZA_SIZE_UPDATED 
                FROM PIZZA_SALES;